LoadModule ibm_ssl_module /QSYS.LIB/QHTTPSVR.LIB/QZSRVSSL.SRVPGM
LoadModule zend_enabler_module /QSYS.LIB/QHTTPSVR.LIB/QZFAST.SRVPGM

Listen *:8080 http
Listen *:8483


ServerName staging_pgsapi.matferbourgeat.com
DirectoryIndex index.php index.html

AddType application/x-httpd-php .php
AddHandler fastcgi-script .php

DefaultFsCCSID 297
DefaultNetCCSID 819

# Charge la config FastCGI séparée
#Include conf/fastcgi.conf

DocumentRoot /www/apis/htdocs
TraceEnable Off
Options -FollowSymLinks
LogFormat "%h %T %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined
LogFormat "%{Cookie}n \"%r\" %t" cookie
LogFormat "%{User-agent}i" agent
LogFormat "%{Referer}i -> %U" referer
LogFormat "%h %l %u %t \"%r\" %>s %b" common
CustomLog logs/access_log combined
LogMaint logs/access_log 7 0
LogMaint logs/error_log 7 0
SetEnvIf "User-Agent" "Mozilla/2" nokeepalive
SetEnvIf "User-Agent" "JDK/1\.0" force-response-1.0
SetEnvIf "User-Agent" "Java/1\.0" force-response-1.0
SetEnvIf "User-Agent" "RealPlayer 4\.0" force-response-1.0
SetEnvIf "User-Agent" "MSIE 4\.0b2;" nokeepalive
SetEnvIf "User-Agent" "MSIE 4\.0b2;" force-response-1.0

SetEnv HTTPS_PORT 8483
<Directory />
     Require all denied
</Directory>


<VirtualHost *:8080>
     ServerName staging_pgsapi.matferbourgeat.com
     DocumentRoot /www/apis/htdocs

     <Directory /www/apis/htdocs>
          Require all granted
          Options -Indexes +FollowSymLinks
          AllowOverride None

          RewriteEngine On
          # Si le fichier/dossier existe, on le sert tel quel (images, css, etc.)
          RewriteCond %{REQUEST_FILENAME} -f [OR]
          RewriteCond %{REQUEST_FILENAME} -d
          RewriteRule ^ - [L]
          # Tout le reste vers routes.php
          RewriteRule ^ routes.php [L,QSA]
     </Directory>

</VirtualHost>
<VirtualHost *:8483>
   SSLEngine On
   SSLAppName QIBM_HTTP_SERVER_APIS2
   SSLProtocolDisable SSLv3 TLSv1 TLSv1.1

   ServerName staging_pgsapi.matferbourgeat.com
   DocumentRoot /www/apis/htdocs

     <Directory /www/apis/htdocs>
          Require all granted
          Options -Indexes +FollowSymLinks
          AllowOverride None

          RewriteEngine On
          # Si le fichier/dossier existe, on le sert tel quel (images, css, etc.)
          RewriteCond %{REQUEST_FILENAME} -f [OR]
          RewriteCond %{REQUEST_FILENAME} -d
          RewriteRule ^ - [L]
          # Tout le reste vers routes.php
          RewriteRule ^ routes.php [L,QSA]
     </Directory>

</VirtualHost>


HTTPSubsystemDesc QHTTPSVR/QHTTPSVR
HTTPStartJobDesc QHTTPSVR/QZHBHTTP
HTTPStartJobQueue *JOBD
HTTPRoutingData *JOBD
