# Configuration originally created by Create HTTP Server wizard on Fri Jan 09 09:52:55 CET 2026
Listen *:8080

# (Recommandé) évite les warnings et certains soucis de vhost
#ServerName localhost

# Index par défaut (sinon / = 403 ou liste de dossier)
DirectoryIndex index.php index.html

# Modure Rewrite pour les routes du serveru d'API
#LoadModule rewrite_module /QSYS.LIB/QHTTPSVR.LIB/QZMODRWRT.SRVPGM
# IBM i FastCGI module (QZFAST) + association des .php
LoadModule zend_enabler_module /QSYS.LIB/QHTTPSVR.LIB/QZFAST.SRVPGM
AddType application/x-httpd-php .php
AddHandler fastcgi-script .php

# CCSID (à ajuster selon ton besoin : 37 = US EBCDIC, 1147 = FR/Euro, 1208 = UTF-8)
# Beaucoup de gens mettent 1208 aujourd’hui pour éviter les galères d’accents.

DefaultFsCCSID 297
DefaultNetCCSID 819

# Charge la config FastCGI séparée
#Include conf/fastcgi.conf

DocumentRoot /www/apis/htdocs
TraceEnable Off
Options -FollowSymLinks
LogFormat "%h %T %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined
LogFormat "%{Cookie}n \"%r\" %t" cookie
LogFormat "%{User-agent}i" agent
LogFormat "%{Referer}i -> %U" referer
LogFormat "%h %l %u %t \"%r\" %>s %b" common
CustomLog logs/access_log combined
ErrorLog logs/error_log
LogMaint logs/access_log 7 0
LogMaint logs/error_log 7 0
SetEnvIf "User-Agent" "Mozilla/2" nokeepalive
SetEnvIf "User-Agent" "JDK/1\.0" force-response-1.0
SetEnvIf "User-Agent" "Java/1\.0" force-response-1.0
SetEnvIf "User-Agent" "RealPlayer 4\.0" force-response-1.0
SetEnvIf "User-Agent" "MSIE 4\.0b2;" nokeepalive
SetEnvIf "User-Agent" "MSIE 4\.0b2;" force-response-1.0

<Directory />
   Require all denied
</Directory>

<Directory /www/apis/htdocs>
   Require all granted
   Options -Indexes +FollowSymLinks
   AllowOverride None

   RewriteEngine On
   # Si le fichier/dossier existe, on le sert tel quel (images, css, etc.)
   RewriteCond %{REQUEST_FILENAME} -f [OR]
   RewriteCond %{REQUEST_FILENAME} -d
   RewriteRule ^ - [L]
   # Tout le reste vers routes.php
   RewriteRule ^ routes.php [L,QSA]

</Directory>

HTTPSubsystemDesc QHTTPSVR/QHTTPSVR
HTTPStartJobDesc QHTTPSVR/QZHBHTTP
HTTPStartJobQueue *JOBD
HTTPRoutingData *JOBD
AccessFileName .htaccess
