<?php
declare(strict_types=1);

namespace App\Reflex;

use App\Reflex\Dépot;
use App\Core\clFichier;

final class HLODPEP extends clFichier
{
    protected static string $table = 'HLODPEP';
    protected static array $primaryKey = ['OECACT', 'OECDPO', 'OENANN', 'OENODP'];
    /** @var array<string,array<string,mixed>> */
    protected static array $columns = [
        'OECACT' => ['label' => 'Code activite',                                                'type' => 'CHAR',    'nullable' => false],
        'OECDPO' => ['label' => 'Code depot physique',                                           'type' => 'CHAR',    'nullable' => false],
        'OENANN' => ['label' => "Numero d'annee",                                                'type' => 'DECIMAL', 'nullable' => false],
        'OENODP' => ['label' => 'Numero ordre de preparation',                                   'type' => 'DECIMAL', 'nullable' => false],
        'OECDDO' => ['label' => "Code donneur d'ordres",                                         'type' => 'CHAR',    'nullable' => false],
        'OERODP' => ['label' => "Reference donneur d'ordres ordre de preparation",              'type' => 'CHAR',    'nullable' => false],
        'OECTPR' => ['label' => 'Code type de preparation',                                      'type' => 'CHAR',    'nullable' => false],
        'OECMOP' => ['label' => 'Code motif ordre de preparation',                               'type' => 'CHAR',    'nullable' => false],
        'OECDES' => ['label' => 'Code destinataire final',                                       'type' => 'CHAR',    'nullable' => false],
        'OECDPD' => ['label' => 'Code depot physique destination (transfert)',                   'type' => 'CHAR',    'nullable' => false],
        'OENEMT' => ['label' => 'Numero emplacement en cours de transfert',                      'type' => 'DECIMAL', 'nullable' => false],
        'OERODD' => ['label' => 'Reference destinataire final ordre de preparation',             'type' => 'CHAR',    'nullable' => false],
        'OESLID' => ['label' => 'Date de livraison demandee odp - siecle',                      'type' => 'DECIMAL', 'nullable' => false],
        'OEALID' => ['label' => 'Date de livraison demandee odp - annee',                       'type' => 'DECIMAL', 'nullable' => false],
        'OEMLID' => ['label' => 'Date de livraison demandee odp - mois',                        'type' => 'DECIMAL', 'nullable' => false],
        'OEJLID' => ['label' => 'Date de livraison demandee odp - jour',                        'type' => 'DECIMAL', 'nullable' => false],
        'OEHDDE' => ['label' => 'Heure debut livraison demandee odp',                           'type' => 'DECIMAL', 'nullable' => false],
        'OEHFDE' => ['label' => 'Heure fin livraison demandee odp',                             'type' => 'DECIMAL', 'nullable' => false],
        'OECTDL' => ['label' => 'Code type date de livraison demandee',                         'type' => 'CHAR',    'nullable' => false],
        'OESLIF' => ['label' => 'Date prevue livraison finale odp - siecle',                    'type' => 'DECIMAL', 'nullable' => false],
        'OEALIF' => ['label' => 'Date prevue livraison finale odp - annee',                     'type' => 'DECIMAL', 'nullable' => false],
        'OEMLIF' => ['label' => 'Date prevue livraison finale odp - mois',                      'type' => 'DECIMAL', 'nullable' => false],
        'OEJLIF' => ['label' => 'Date prevue livraison finale odp - jour',                      'type' => 'DECIMAL', 'nullable' => false],
        'OEHDLF' => ['label' => 'Heure debut prevue livraison finale odp',                      'type' => 'DECIMAL', 'nullable' => false],
        'OEHFLF' => ['label' => 'Heure fin prevue livraison finale odp',                        'type' => 'DECIMAL', 'nullable' => false],
        'OESRVF' => ['label' => 'Date RV destinataire final odp - siecle',                      'type' => 'DECIMAL', 'nullable' => false],
        'OEARVF' => ['label' => 'Date RV destinataire final odp - annee',                       'type' => 'DECIMAL', 'nullable' => false],
        'OEMRVF' => ['label' => 'Date RV destinataire final odp - mois',                        'type' => 'DECIMAL', 'nullable' => false],
        'OEJRVF' => ['label' => 'Date RV destinataire final odp - jour',                        'type' => 'DECIMAL', 'nullable' => false],
        'OEHDRF' => ['label' => 'Heure debut RV destinataire final odp',                        'type' => 'DECIMAL', 'nullable' => false],
        'OEHFRF' => ['label' => 'Heure fin RV destinataire final odp',                          'type' => 'DECIMAL', 'nullable' => false],
        'OECDEI' => ['label' => 'Code destinataire intermediaire',                              'type' => 'CHAR',    'nullable' => false],
        'OERODI' => ['label' => 'Reference dest. intermediaire ordre de preparation',           'type' => 'CHAR',    'nullable' => false],
        'OESLII' => ['label' => 'Date prevue livraison intermediaire odp - siecle',            'type' => 'DECIMAL', 'nullable' => false],
        'OEALII' => ['label' => 'Date prevue livraison intermediaire odp - annee',             'type' => 'DECIMAL', 'nullable' => false],
        'OEMLII' => ['label' => 'Date prevue livraison intermediaire odp - mois',              'type' => 'DECIMAL', 'nullable' => false],
        'OEJLII' => ['label' => 'Date prevue livraison intermediaire odp - jour',              'type' => 'DECIMAL', 'nullable' => false],
        'OEHDLI' => ['label' => 'Heure debut prevue livraison intermediaire odp',              'type' => 'DECIMAL', 'nullable' => false],
        'OEHFLI' => ['label' => 'Heure fin prevue livraison intermediaire odp',                'type' => 'DECIMAL', 'nullable' => false],
        'OESRVI' => ['label' => 'Date RV destinataire intermediaire odp - siecle',             'type' => 'DECIMAL', 'nullable' => false],
        'OEARVI' => ['label' => 'Date RV destinataire intermediaire odp - annee',              'type' => 'DECIMAL', 'nullable' => false],
        'OEMRVI' => ['label' => 'Date RV destinataire intermediaire odp - mois',               'type' => 'DECIMAL', 'nullable' => false],
        'OEJRVI' => ['label' => 'Date RV destinataire intermediaire odp - jour',               'type' => 'DECIMAL', 'nullable' => false],
        'OEHDRI' => ['label' => 'Heure debut RV destinataire intermediaire odp',               'type' => 'DECIMAL', 'nullable' => false],
        'OEHFRI' => ['label' => 'Heure fin RV destinataire intermediaire odp',                 'type' => 'DECIMAL', 'nullable' => false],
        'OESPRP' => ['label' => 'Date de preparation prevue odp - siecle',                     'type' => 'DECIMAL', 'nullable' => false],
        'OEAPRP' => ['label' => 'Date de preparation prevue odp - annee',                      'type' => 'DECIMAL', 'nullable' => false],
        'OEMPRP' => ['label' => 'Date de preparation prevue odp - mois',                       'type' => 'DECIMAL', 'nullable' => false],
        'OEJPRP' => ['label' => 'Date de preparation prevue odp - jour',                       'type' => 'DECIMAL', 'nullable' => false],
        'OENEMP' => ['label' => 'Numero emplacement de mise a disposition',                    'type' => 'DECIMAL', 'nullable' => false],
        'OET1CO' => ['label' => 'Total niveau 1 commande ordre de preparation',                'type' => 'DECIMAL', 'nullable' => false],
        'OET2CO' => ['label' => 'Total niveau 2 commande ordre de preparation',                'type' => 'DECIMAL', 'nullable' => false],
        'OET3CO' => ['label' => 'Total niveau 3 commande ordre de preparation',                'type' => 'DECIMAL', 'nullable' => false],
        'OETBCO' => ['label' => 'Total en VL de base commande ordre de preparation',           'type' => 'DECIMAL', 'nullable' => false],
        'OETT1C' => ['label' => 'Total general niveau 1 commande ordre de prep.',              'type' => 'DECIMAL', 'nullable' => false],
        'OETT2C' => ['label' => 'Total general niveau 2 commande ordre de prep.',              'type' => 'DECIMAL', 'nullable' => false],
        'OETPNC' => ['label' => 'Poids net total commande ordre de preparation',               'type' => 'DECIMAL', 'nullable' => false],
        'OETPOC' => ['label' => 'Poids brut total commande ordre de preparation',              'type' => 'DECIMAL', 'nullable' => false],
        'OETVOC' => ['label' => 'Volume total commande ordre de preparation',                  'type' => 'DECIMAL', 'nullable' => false],
        'OET1OD' => ['label' => 'Total niveau 1 a preparer ordre de preparation',              'type' => 'DECIMAL', 'nullable' => false],
        'OET2OD' => ['label' => 'Total niveau 2 a preparer ordre de preparation',              'type' => 'DECIMAL', 'nullable' => false],
        'OET3OD' => ['label' => 'Total niveau 3 a preparer ordre de preparation',              'type' => 'DECIMAL', 'nullable' => false],
        'OETBOD' => ['label' => 'Total en VL de base a preparer ordre de prep.',               'type' => 'DECIMAL', 'nullable' => false],
        'OETT1O' => ['label' => 'Total general niveau 1 a prep ordre de preparation',          'type' => 'DECIMAL', 'nullable' => false],
        'OETT2O' => ['label' => 'Total general niveau 2 a prep ordre de preparation',          'type' => 'DECIMAL', 'nullable' => false],
        'OETPNO' => ['label' => 'Poids net total a preparer ordre de preparation',             'type' => 'DECIMAL', 'nullable' => false],
        'OETPOD' => ['label' => 'Poids brut total a preparer ordre de preparation',            'type' => 'DECIMAL', 'nullable' => false],
        'OETVOD' => ['label' => 'Volume total a preparer ordre de preparation',                'type' => 'DECIMAL', 'nullable' => false],
        'OESLAN' => ['label' => 'Date lancement - siecle',                                     'type' => 'DECIMAL', 'nullable' => false],
        'OEALAN' => ['label' => 'Date lancement - annee',                                      'type' => 'DECIMAL', 'nullable' => false],
        'OEMLAN' => ['label' => 'Date lancement - mois',                                       'type' => 'DECIMAL', 'nullable' => false],
        'OEJLAN' => ['label' => 'Date lancement - jour',                                       'type' => 'DECIMAL', 'nullable' => false],
        'OECDLA' => ['label' => 'Code lancement',                                              'type' => 'CHAR',    'nullable' => false],
        'OECCPL' => ['label' => 'Code circuit de prelevement',                                 'type' => 'CHAR',    'nullable' => false],
        'OECQTP' => ['label' => 'Code qualite transport',                                      'type' => 'CHAR',    'nullable' => false],
        'OECFPR' => ['label' => 'Code famille de preparation',                                 'type' => 'CHAR',    'nullable' => false],
        'OECRGC' => ['label' => 'Code regroupement chargement',                                'type' => 'CHAR',    'nullable' => false],
        'OECRGE' => ['label' => 'Code regroupement expedition',                                'type' => 'CHAR',    'nullable' => false],
        'OENSEX' => ['label' => 'Numero de sequence livraison expedition ds le chg',           'type' => 'DECIMAL', 'nullable' => false],
        'OESCHG' => ['label' => 'Date chargement - siecle',                                    'type' => 'DECIMAL', 'nullable' => false],
        'OEACHG' => ['label' => 'Date chargement - annee',                                     'type' => 'DECIMAL', 'nullable' => false],
        'OEMCHG' => ['label' => 'Date chargement - mois',                                      'type' => 'DECIMAL', 'nullable' => false],
        'OEJCHG' => ['label' => 'Date chargement - jour',                                      'type' => 'DECIMAL', 'nullable' => false],
        'OECCHA' => ['label' => 'Code chargement',                                             'type' => 'CHAR',    'nullable' => false],
        'OESGPR' => ['label' => 'Date generation preparation - siecle',                        'type' => 'DECIMAL', 'nullable' => false],
        'OEAGPR' => ['label' => 'Date generation preparation - annee',                         'type' => 'DECIMAL', 'nullable' => false],
        'OEMGPR' => ['label' => 'Date generation preparation - mois',                          'type' => 'DECIMAL', 'nullable' => false],
        'OEJGPR' => ['label' => 'Date generation preparation - jour',                          'type' => 'DECIMAL', 'nullable' => false],
        'OEHGPR' => ['label' => 'Heure generation preparation',                                'type' => 'DECIMAL', 'nullable' => false],
        'OECPGP' => ['label' => 'Code programme generation preparation',                       'type' => 'CHAR',    'nullable' => false],
        'OECUGP' => ['label' => 'Code utilisateur generation preparation',                     'type' => 'CHAR',    'nullable' => false],
        'OESVOD' => ['label' => 'Date validation odp - siecle',                                'type' => 'DECIMAL', 'nullable' => false],
        'OEAVOD' => ['label' => 'Date validation odp - annee',                                 'type' => 'DECIMAL', 'nullable' => false],
        'OEMVOD' => ['label' => 'Date validation odp - mois',                                  'type' => 'DECIMAL', 'nullable' => false],
        'OEJVOD' => ['label' => 'Date validation odp - jour',                                  'type' => 'DECIMAL', 'nullable' => false],
        'OEHVOD' => ['label' => 'Heure validation odp',                                        'type' => 'DECIMAL', 'nullable' => false],
        'OETPTG' => ['label' => 'Top ordre de preparation protege',                            'type' => 'CHAR',    'nullable' => false],
        'OETLIG' => ['label' => 'Top livraison globalisee ordre de preparation',               'type' => 'CHAR',    'nullable' => false],
        'OETDEI' => ['label' => "Top destinataire intermediaire pour l'odp",                  'type' => 'CHAR',    'nullable' => false],
        'OETSVO' => ['label' => 'Top sortie stock a la validation preparation',                'type' => 'CHAR',    'nullable' => false],
        'OETBEC' => ['label' => "Top edition du bordereau d'eclatement odp (interm)",         'type' => 'CHAR',    'nullable' => false],
        'OETBLE' => ['label' => 'Top edition des BL finaux odp (intermediaire)',               'type' => 'CHAR',    'nullable' => false],
        'OETRVF' => ['label' => 'Top rendez-vous pris destinataire final odp',                 'type' => 'CHAR',    'nullable' => false],
        'OETRVI' => ['label' => 'Top rendez-vous pris destinataire intermed. odp',             'type' => 'CHAR',    'nullable' => false],
        'OETENC' => ['label' => "Top preparation en cours de generation pour l'odp",           'type' => 'CHAR',    'nullable' => false],
        'OETPRG' => ['label' => "Top preparation generee pour l'odp",                          'type' => 'CHAR',    'nullable' => false],
        'OETODV' => ['label' => 'Top ordre de preparation valide',                             'type' => 'CHAR',    'nullable' => false],
        'OENOBJ' => ['label' => "Numero d'objet",                                              'type' => 'DECIMAL', 'nullable' => false],
        'OENCOM' => ['label' => 'Numero de commentaire',                                       'type' => 'DECIMAL', 'nullable' => false],
        'OESCRE' => ['label' => 'Date de creation - siecle',                                   'type' => 'DECIMAL', 'nullable' => false],
        'OEACRE' => ['label' => 'Date de creation - annee',                                    'type' => 'DECIMAL', 'nullable' => false],
        'OEMCRE' => ['label' => 'Date de creation - mois',                                     'type' => 'DECIMAL', 'nullable' => false],
        'OEJCRE' => ['label' => 'Date de creation - jour',                                     'type' => 'DECIMAL', 'nullable' => false],
        'OEHCRE' => ['label' => 'Heure de creation',                                           'type' => 'DECIMAL', 'nullable' => false],
        'OECPCR' => ['label' => 'Code programme creation',                                     'type' => 'CHAR',    'nullable' => false],
        'OECUCR' => ['label' => 'Code utilisateur creation',                                   'type' => 'CHAR',    'nullable' => false],
        'OESMAJ' => ['label' => 'Date de derniere mise a jour - siecle',                       'type' => 'DECIMAL', 'nullable' => false],
        'OEAMAJ' => ['label' => 'Date de derniere mise a jour - annee',                        'type' => 'DECIMAL', 'nullable' => false],
        'OEMMAJ' => ['label' => 'Date de derniere mise a jour - mois',                         'type' => 'DECIMAL', 'nullable' => false],
        'OEJMAJ' => ['label' => 'Date de derniere mise a jour - jour',                         'type' => 'DECIMAL', 'nullable' => false],
        'OEHMAJ' => ['label' => 'Heure de derniere mise a jour',                               'type' => 'DECIMAL', 'nullable' => false],
        'OECUMJ' => ['label' => 'Code utilisateur derniere mise a jour',                       'type' => 'CHAR',    'nullable' => false],
        'OETOPD' => ['label' => 'Top desactivation',                                           'type' => 'CHAR',    'nullable' => false],
    ];

    private static function libraryOf(string $CodeActivité): ?string
    {
        $company = Dépot::get($CodeActivité);
        if (!$company) return null;

        $library = (string)($company['library'] ?? '');
        return $library !== '' ? $library : null;
    }
}
