<?php
declare(strict_types=1);

namespace App\Reflex;

use App\Domain\Company;
use App\Core\clFichier;

final class HLPRPLP extends clFichier
{
    protected static string $table = 'HLPRPLP';
    protected static array $primaryKey = ['P1CACT', 'P1CDPO', 'P1NANN', 'P1NLPR'];
    /** @var array<string,array<string,mixed>> */
    protected static array $columns = [
        'P1CACT' => ['label' => 'Code activite',                                             'type' => 'CHAR',    'nullable' => false],
        'P1CDPO' => ['label' => 'Code depot physique',                                        'type' => 'CHAR',    'nullable' => false],
        'P1NANN' => ['label' => "Numero d'annee ligne de preparation",                        'type' => 'DECIMAL', 'nullable' => false],
        'P1NLPR' => ['label' => 'Numero de ligne de preparation',                             'type' => 'DECIMAL', 'nullable' => false],
        'P1NANP' => ['label' => "Numero d'annee preparation",                                 'type' => 'DECIMAL', 'nullable' => false],
        'P1NPRE' => ['label' => 'Numero de preparation',                                      'type' => 'DECIMAL', 'nullable' => false],
        'PECDOD' => ['label' => 'Code depot physique ordre de preparation',                   'type' => 'CHAR',    'nullable' => false],
        'P1NANO' => ['label' => "Numero d'annee ordre de preparation",                        'type' => 'DECIMAL', 'nullable' => false],
        'P1NODP' => ['label' => 'Numero ordre de preparation',                                'type' => 'DECIMAL', 'nullable' => false],
        'P1NLOP' => ['label' => 'Numero de ligne ordre de preparation',                       'type' => 'DECIMAL', 'nullable' => false],
        'P1CART' => ['label' => 'Code article',                                               'type' => 'CHAR',    'nullable' => false],
        'P1CVLA' => ['label' => 'Code variante logistique article',                           'type' => 'CHAR',    'nullable' => false],
        'P1CPRP' => ['label' => 'Code proprietaire',                                          'type' => 'CHAR',    'nullable' => false],
        'P1CQAL' => ['label' => 'Code qualite',                                               'type' => 'CHAR',    'nullable' => false],
        'P1CKIL' => ['label' => 'Code kit ligne de preparation',                              'type' => 'CHAR',    'nullable' => false],
        'P1LOTP' => ['label' => 'Lot 1 ligne de preparation',                                 'type' => 'CHAR',    'nullable' => false],
        'P1LO2P' => ['label' => 'Lot 2 ligne de preparation',                                 'type' => 'CHAR',    'nullable' => false],
        'P1LO3P' => ['label' => 'Lot 3 ligne de preparation',                                 'type' => 'CHAR',    'nullable' => false],
        'P1CDES' => ['label' => 'Code destinataire final',                                    'type' => 'CHAR',    'nullable' => false],
        'P1QODP' => ['label' => 'Quantite en VL de base a preparer odp ligne prepa',         'type' => 'DECIMAL', 'nullable' => false],
        'P1PNOD' => ['label' => 'Poids net a preparer odp ligne prepa',                       'type' => 'DECIMAL', 'nullable' => false],
        'P1QAPR' => ['label' => 'Quantite en VL de base a preparer ligne prepa',             'type' => 'DECIMAL', 'nullable' => false],
        'P1PAPN' => ['label' => 'Poids net a preparer ligne prepa',                           'type' => 'DECIMAL', 'nullable' => false],
        'P1QPRE' => ['label' => 'Quantite en VL de base validee ligne prepa',                'type' => 'DECIMAL', 'nullable' => false],
        'P1PNPR' => ['label' => 'Poids net valide ligne prepa',                               'type' => 'DECIMAL', 'nullable' => false],
        'P1QRAG' => ['label' => 'Qte en VL de base reliquat a generer ligne prepa',          'type' => 'DECIMAL', 'nullable' => false],
        'P1PNRA' => ['label' => 'Poids net reliquat a generer ligne prepa',                   'type' => 'DECIMAL', 'nullable' => false],
        'P1QRGE' => ['label' => 'Qte en VL de base reliquat genere ligne prepa',             'type' => 'DECIMAL', 'nullable' => false],
        'P1PNRG' => ['label' => 'Poids net reliquat genere ligne prepa',                      'type' => 'DECIMAL', 'nullable' => false],
        'P1NQSB' => ['label' => 'Numerateur quantite substituee ligne prepa',                 'type' => 'DECIMAL', 'nullable' => false],
        'P1DQSB' => ['label' => 'Denominateur quantite substituee ligne prepa',               'type' => 'DECIMAL', 'nullable' => false],
        'P1PNSU' => ['label' => 'Poids net substitue ligne prepa',                             'type' => 'DECIMAL', 'nullable' => false],
        'P1NQAM' => ['label' => 'Numerateur quantite a mettre en lanc ligne prepa',           'type' => 'DECIMAL', 'nullable' => false],
        'P1DQAM' => ['label' => 'Denominateur quantite a mettre en lanc ligne prepa',         'type' => 'DECIMAL', 'nullable' => false],
        'P1PAML' => ['label' => 'Poids net a mettre en lancement ligne prepa',                'type' => 'DECIMAL', 'nullable' => false],
        'P1SSCA' => ['label' => 'Siecle lancement',                                            'type' => 'DECIMAL', 'nullable' => false],
        'P1ANCA' => ['label' => 'Annee lancement',                                             'type' => 'DECIMAL', 'nullable' => false],
        'P1MOCA' => ['label' => 'Mois lancement',                                              'type' => 'DECIMAL', 'nullable' => false],
        'P1JOCA' => ['label' => 'Jour lancement',                                              'type' => 'DECIMAL', 'nullable' => false],
        'P1CDLA' => ['label' => 'Code lancement',                                              'type' => 'CHAR',    'nullable' => false],
        'P1SALL' => ['label' => 'Date affectation lancement ligne prepa - siecle',            'type' => 'DECIMAL', 'nullable' => false],
        'P1AALL' => ['label' => 'Date affectation lancement ligne prepa - annee',             'type' => 'DECIMAL', 'nullable' => false],
        'P1MALL' => ['label' => 'Date affectation lancement ligne prepa - mois',              'type' => 'DECIMAL', 'nullable' => false],
        'P1JALL' => ['label' => 'Date affectation lancement ligne prepa - jour',              'type' => 'DECIMAL', 'nullable' => false],
        'P1HALL' => ['label' => 'Heure affectation lancement ligne prepa',                    'type' => 'DECIMAL', 'nullable' => false],
        'P1PALL' => ['label' => 'Code programme affectation lancement ligne prepa',           'type' => 'CHAR',    'nullable' => false],
        'P1UALL' => ['label' => 'Code utilisateur affectation lancement ligne prepa',         'type' => 'CHAR',    'nullable' => false],
        'P1NMEL' => ['label' => 'Numerateur quantite mise en lancement',                       'type' => 'DECIMAL', 'nullable' => false],
        'P1DMEL' => ['label' => 'Denominateur quantite mise en lancement',                     'type' => 'DECIMAL', 'nullable' => false],
        'P1PNMA' => ['label' => 'Poids net mis en lancement ligne prepa',                      'type' => 'DECIMAL', 'nullable' => false],
        'P1NATT' => ['label' => 'Numerateur quantite attribuee lancement',                     'type' => 'DECIMAL', 'nullable' => false],
        'P1DATT' => ['label' => 'Denominateur quantite attribuee lancement',                   'type' => 'DECIMAL', 'nullable' => false],
        'P1PNAL' => ['label' => 'Poids net attribue lancement ligne prepa',                    'type' => 'DECIMAL', 'nullable' => false],
        'P1NQSL' => ['label' => 'Numerateur quantite substituee lancement',                    'type' => 'DECIMAL', 'nullable' => false],
        'P1DSUL' => ['label' => 'Denominateur quantite substituee lancement',                  'type' => 'DECIMAL', 'nullable' => false],
        'P1PNSL' => ['label' => 'Poids net substitue lancement ligne prepa',                   'type' => 'DECIMAL', 'nullable' => false],
        'P1NNSL' => ['label' => 'Numerateur quantite non servie lancement',                    'type' => 'DECIMAL', 'nullable' => false],
        'P1DNSL' => ['label' => 'Denominateur quantite non servie lancement',                  'type' => 'DECIMAL', 'nullable' => false],
        'P1PNNS' => ['label' => 'Poids net non servi lancement ligne prepa',                   'type' => 'DECIMAL', 'nullable' => false],
        'P1RRSO' => ['label' => 'Reference reservation odp',                                   'type' => 'CHAR',    'nullable' => false],
        'P1SQTR' => ['label' => 'Sequence de tri du service',                                  'type' => 'CHAR',    'nullable' => false],
        'P1CPRS' => ['label' => 'Code priorite de service',                                    'type' => 'CHAR',    'nullable' => false],
        'P1PTMP' => ['label' => 'Pourcentage tolerance en - pour quantite prepa ligne prepa', 'type' => 'DECIMAL', 'nullable' => false],
        'P1PTPP' => ['label' => 'Pourcentage tolerance en + pour quantite prepa ligne prepa', 'type' => 'DECIMAL', 'nullable' => false],
        'P1Q1IP' => ['label' => "Unite d'interception - Quantite niveau 1",                   'type' => 'DECIMAL', 'nullable' => false],
        'P1Q2IP' => ['label' => "Unite d'interception - Quantite niveau 2",                   'type' => 'DECIMAL', 'nullable' => false],
        'P1Q3IP' => ['label' => "Unite d'interception - Quantite niveau 3",                   'type' => 'DECIMAL', 'nullable' => false],
        'P1QBIP' => ['label' => "Unite d'interception - Quantite en VL de base",              'type' => 'DECIMAL', 'nullable' => false],
        'P1IHMP' => ['label' => "Delai mini d'interception - Nombre heures minutes",          'type' => 'DECIMAL', 'nullable' => false],
        'P1IHXP' => ['label' => "Delai maxi d'interception - Nombre heures minutes",          'type' => 'DECIMAL', 'nullable' => false],
        'P1NJMF' => ['label' => "Nombre de jours mini date d'ordo force ligne prepa",         'type' => 'DECIMAL', 'nullable' => false],
        'P1CCPL' => ['label' => 'Code circuit de prelevement',                                 'type' => 'CHAR',    'nullable' => false],
        'P1SVLP' => ['label' => 'Date validation ligne de preparation - siecle',               'type' => 'DECIMAL', 'nullable' => false],
        'P1AVLP' => ['label' => 'Date validation ligne de preparation - annee',                'type' => 'DECIMAL', 'nullable' => false],
        'P1MVLP' => ['label' => 'Date validation ligne de preparation - mois',                 'type' => 'DECIMAL', 'nullable' => false],
        'P1JVLP' => ['label' => 'Date validation ligne de preparation - jour',                 'type' => 'DECIMAL', 'nullable' => false],
        'P1HVLP' => ['label' => 'Heure validation ligne de preparation - jour',                'type' => 'DECIMAL', 'nullable' => false],
        'P1CACR' => ['label' => 'Code activite ligne prepa de reliquat corresp.',             'type' => 'CHAR',    'nullable' => false],
        'P1CDPR' => ['label' => 'Code depot physique ligne prepa de reliquat corr.',          'type' => 'CHAR',    'nullable' => false],
        'P1NANR' => ['label' => "Numero d'annee ligne prepa de reliquat corresp.",            'type' => 'DECIMAL', 'nullable' => false],
        'P1NLRE' => ['label' => 'Numero de ligne de preparation de reliquat corresp',         'type' => 'DECIMAL', 'nullable' => false],
        'P1TMEL' => ['label' => 'Top mise en lancement possible ligne de prepa.',             'type' => 'CHAR',    'nullable' => false],
        'P1TCTL' => ['label' => 'Top calcul lancement termine pour la ligne prepa',           'type' => 'CHAR',    'nullable' => false],
        'P1TLRE' => ['label' => 'Top ligne de preparation de reliquat',                        'type' => 'CHAR',    'nullable' => false],
        'P1TSOR' => ['label' => 'Top service obligatoire sur reference reservation',           'type' => 'CHAR',    'nullable' => false],
        'P1TILP' => ['label' => 'Top interception ligne de preparation',                       'type' => 'CHAR',    'nullable' => false],
        'P1TIML' => ['label' => 'Top intercepter meme si mis en lancement',                   'type' => 'CHAR',    'nullable' => false],
        'P1TCIN' => ['label' => 'Top calculer meme si interception',                           'type' => 'CHAR',    'nullable' => false],
        'P1TALL' => ['label' => 'Top ligne en allotissement',                                  'type' => 'CHAR',    'nullable' => false],
        'P1TRLP' => ['label' => 'Top stock reserve ligne de preparation',                      'type' => 'CHAR',    'nullable' => false],
        'P1TDFP' => ['label' => "Top delai mini de date d'ordo force preparation",            'type' => 'CHAR',    'nullable' => false],
        'P1TCHP' => ['label' => 'Top chainage possible pour ligne preparation',                'type' => 'CHAR',    'nullable' => false],
        'P1TSUP' => ['label' => 'Top substitution possible pour ligne preparation',            'type' => 'CHAR',    'nullable' => false],
        'P1TSLO' => ['label' => 'Top substitution sur ligne odp',                              'type' => 'CHAR',    'nullable' => false],
        'P1TVIP' => ['label' => 'Top VL indifferente ligne prepa',                             'type' => 'CHAR',    'nullable' => false],
        'P1TKIP' => ['label' => 'Top kit complet',                                             'type' => 'CHAR',    'nullable' => false],
        'P1TVLP' => ['label' => 'Top ligne preparation validee',                               'type' => 'CHAR',    'nullable' => false],
        'P1NAPL' => ['label' => "Numero d'annee prelevement pour reprise",                    'type' => 'DECIMAL', 'nullable' => false],
        'P1NPRL' => ['label' => 'Numero de prelevement pour reprise',                          'type' => 'DECIMAL', 'nullable' => false],
        'P1NOBJ' => ['label' => "Numero d'objet",                                              'type' => 'DECIMAL', 'nullable' => false],
        'P1NCOM' => ['label' => 'Numero de commentaire',                                       'type' => 'DECIMAL', 'nullable' => false],
        'P1SCRE' => ['label' => 'Date de creation - siecle',                                   'type' => 'DECIMAL', 'nullable' => false],
        'P1ACRE' => ['label' => 'Date de creation - annee',                                    'type' => 'DECIMAL', 'nullable' => false],
        'P1MCRE' => ['label' => 'Date de creation - mois',                                     'type' => 'DECIMAL', 'nullable' => false],
        'P1JCRE' => ['label' => 'Date de creation - jour',                                     'type' => 'DECIMAL', 'nullable' => false],
        'P1HCRE' => ['label' => 'Heure de creation',                                           'type' => 'DECIMAL', 'nullable' => false],
        'P1CPCR' => ['label' => 'Code programme creation',                                     'type' => 'CHAR',    'nullable' => false],
        'P1SMAJ' => ['label' => 'Date de derniere mise a jour - siecle',                      'type' => 'DECIMAL', 'nullable' => false],
        'P1AMAJ' => ['label' => 'Date de derniere mise a jour - annee',                       'type' => 'DECIMAL', 'nullable' => false],
        'P1MMAJ' => ['label' => 'Date de derniere mise a jour - mois',                        'type' => 'DECIMAL', 'nullable' => false],
        'P1JMAJ' => ['label' => 'Date de derniere mise a jour - jour',                        'type' => 'DECIMAL', 'nullable' => false],
        'P1HMAJ' => ['label' => 'Heure de derniere mise a jour',                              'type' => 'DECIMAL', 'nullable' => false],
        'P1CUMJ' => ['label' => 'Code utilisateur derniere mise a jour',                      'type' => 'CHAR',    'nullable' => false],
        'P1TOPD' => ['label' => 'Top desactivation',                                           'type' => 'CHAR',    'nullable' => false],
    ];

    private static function libraryOf(string $companyCode): ?string
    {
        $company = Company::get($companyCode);
        if (!$company) return null;

        $library = (string)($company['reflex_library'] ?? '');
        return $library !== '' ? $library : null;
    }
}
